// Mock data for UI demonstration without a live Supabase connection
export const MOCK_ITEMS = [
  {
    id: '1',
    title: 'MacBook Pro 13" (2020)',
    price: 45000,
    category: 'Electronics',
    condition: 'Good',
    description: 'Excellent condition MacBook Pro with M1 chip. Minor scratches on the bottom. Comes with original charger. Battery health 92%.',
    images: ['https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400&h=300&fit=crop'],
    status: 'approved',
    seller_id: 'mock-user-1',
    seller_name: 'Arjun M.',
    seller_trust: 4.8,
    seller_listings: 12,
    posted_date: '2024-01-15',
    college: 'NIT Trichy',
    views: 342, wishlistCount: 45,
  },
  {
    id: '2',
    title: 'Engineering Mathematics Textbook',
    price: 350,
    category: 'Books',
    condition: 'Like New',
    description: 'Advanced Engineering Mathematics by Erwin Kreyszig, 10th edition. Only used for one semester. No highlights, clean pages.',
    images: ['https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=300&fit=crop'],
    status: 'approved',
    seller_id: 'mock-user-2',
    seller_name: 'Priya K.',
    seller_trust: 4.5,
    seller_listings: 5,
    posted_date: '2024-01-18',
    college: 'IIT Madras',
    views: 124, wishlistCount: 8,
  },
  {
    id: '3',
    title: 'Scientific Calculator (Casio FX-991EX)',
    price: 800,
    category: 'Stationery',
    condition: 'Good',
    description: 'Casio FX-991EX with all functions working perfectly. Cover included. Battery recently replaced.',
    images: ['https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=400&h=300&fit=crop'],
    status: 'approved',
    seller_id: 'mock-user-3',
    seller_name: 'Rahul S.',
    seller_trust: 4.2,
    seller_listings: 3,
    posted_date: '2024-01-20',
    college: 'VIT Vellore',
    views: 56, wishlistCount: 4,
  },
  {
    id: '4',
    title: 'Ergonomic Study Chair',
    price: 2500,
    category: 'Furniture',
    condition: 'Fair',
    description: 'Comfortable mesh back chair with adjustable height. Perfect for long study sessions. Some wear on the seat cushion.',
    images: ['https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=400&h=300&fit=crop'],
    status: 'approved',
    seller_id: 'mock-user-4',
    seller_name: 'Sana B.',
    seller_trust: 4.9,
    seller_listings: 8,
    posted_date: '2024-01-22',
    college: 'BITS Pilani',
    views: 210, wishlistCount: 22,
  },
  {
    id: '5',
    title: 'Sony WH-1000XM4 Headphones',
    price: 9500,
    category: 'Electronics',
    condition: 'Like New',
    description: 'Noise cancelling headphones in near-perfect condition. Used for only 2 months. Original box and accessories included.',
    images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=300&fit=crop'],
    status: 'approved',
    seller_id: 'mock-user-5',
    seller_name: 'Dev P.',
    seller_trust: 4.7,
    seller_listings: 6,
    posted_date: '2024-01-23',
    college: 'IIT Bombay',
    views: 450, wishlistCount: 65,
  },
  {
    id: '6',
    title: 'Organic Chemistry - Morrison Boyd',
    price: 450,
    category: 'Books',
    condition: 'Good',
    description: 'Classic organic chemistry textbook. Some pencil markings that can be erased. Complete text with all chapters.',
    images: ['https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400&h=300&fit=crop'],
    status: 'approved',
    seller_id: 'mock-user-6',
    seller_name: 'Meera V.',
    seller_trust: 4.3,
    seller_listings: 15,
    posted_date: '2024-01-25',
    college: 'Anna University',
    views: 75, wishlistCount: 3,
  },
  {
    id: '7',
    title: 'Portable Laptop Stand + Mouse',
    price: 1200,
    category: 'Electronics',
    condition: 'Like New',
    description: 'Aluminum foldable laptop stand + wireless mouse combo. Stand fits 11-17 inch laptops. Mouse has new batteries.',
    images: ['https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400&h=300&fit=crop'],
    status: 'sold',
    seller_id: 'mock-user-7',
    seller_name: 'Kiran J.',
    seller_trust: 4.6,
    seller_listings: 4,
    posted_date: '2024-01-10',
    college: 'SRM University',
    views: 89, wishlistCount: 12,
  },
  {
    id: '8',
    title: 'Mini Refrigerator (115L)',
    price: 5500,
    category: 'Furniture',
    condition: 'Good',
    description: 'Perfect for hostel room. 115L capacity, works perfectly, energy efficient. Compact size 55x45x55 cm.',
    images: ['https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=400&h=300&fit=crop'],
    status: 'pending',
    seller_id: 'mock-user-8',
    seller_name: 'Anjali R.',
    seller_trust: 4.1,
    seller_listings: 2,
    posted_date: '2024-01-28',
    college: 'Manipal University',
    views: 45, wishlistCount: 8,
  },
]

export const MOCK_USER = {
  id: 'current-user',
  name: 'Lithes M.',
  email: 'lithes@college.edu',
  college: 'Your College',
  trust_score: 4.6,
  listings_count: 3,
  joined_date: '2023-09-01',
}

export const CATEGORIES = [
  'All Categories',
  'Books', 'Electronics', 'Stationery', 'Lab Equipment', 
  'Furniture', 'Hostel Essentials', 'Clothing', 'Sports Equipment', 
  'Gaming', 'Toys', 'Collectibles', 'Art Supplies', 
  'Musical Instruments', 'Kitchen Items', 'Other'
]

export const CONDITIONS = ['Any Condition', 'Like New', 'Good', 'Fair', 'Poor']

export const PRICE_SUGGESTIONS = {
  Electronics: { min: 500, max: 50000 },
  Books: { min: 50, max: 1500 },
  Stationery: { min: 50, max: 2000 },
  Furniture: { min: 500, max: 15000 },
  Clothing: { min: 100, max: 3000 },
  'Sports Equipment': { min: 200, max: 10000 },
  'Lab Equipment': { min: 100, max: 5000 },
  'Hostel Essentials': { min: 100, max: 3000 },
  Gaming: { min: 500, max: 30000 },
  'Musical Instruments': { min: 1000, max: 25000 },
  Other: { min: 100, max: 5000 },
}

export const MOCK_ACTIVITY_TIMELINE = [
  { id: '1', type: 'message', content: 'Your item "Sony WH-1000XM4" received a new buyer request.', time: '2h ago' },
  { id: '2', type: 'wishlist', content: 'Someone added "Engineering Mathematics" to their wishlist.', time: '5h ago' },
  { id: '3', type: 'approved', content: 'Your listing "MacBook Pro 13"" got approved.', time: '1d ago' },
  { id: '4', type: 'sold', content: 'You marked "Portable Laptop Stand" as sold.', time: '2d ago' },
  { id: '5', type: 'posted', content: 'You posted "Engineering Mathematics Textbook".', time: '3d ago' },
]
